# -*- coding: utf-8 -*-
"""Análise de Dados de Mercado

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XhEBDRof7coqSHqrUtAzglfNSIlTDK6d
"""

import pandas as pd

arquivo = pd.read_csv("arquivo.csv")
display(arquivo)


# Qual foi o faturamento total do mercado em 2020?
# Qual foi o ticket médio do mercado em junho de 2020?
# Qual foi o mês com o maior número de clientes no ano de 2021?
# Qual foi o faturamento médio mensal do mercado em 2021?
# Qual foi o crescimento percentual do faturamento de janeiro de 2020 para janeiro de 2021?
# Qual foi o mês em que o número de funcionários aumentou?
# Qual foi o faturamento médio por cliente em outubro de 2021?
# Qual foi a média de clientes atendidos por funcionário em julho de 2020?
# Qual foi o mês em que o mercado teve o maior número de vendas?
# Qual foi o ticket médio em dezembro de 2020?

"""# Qual foi o faturamento total do mercado em 2020?"""

import pandas as pd

# Carrega o arquivo CSV em um dataframe
arquivo = pd.read_csv("arquivo.csv")

# Converte a coluna "Ano" para string
arquivo['Ano'] = arquivo['Ano'].astype(str)

# Selecione as linhas em que a coluna "Ano" começa com "2020"
df_2020 = arquivo.loc[arquivo['Ano'].str.startswith('2020'), :]

# Calcule a soma da coluna "Faturamento" no novo dataframe
total_faturamento_2020 = df_2020['Faturamento'].sum()


print(total_faturamento_2020)

"""# Qual foi o ticket médio do mercado em junho de 2020?"""

# Carregar o arquivo CSV em um dataframe
arquivo = pd.read_csv("arquivo.csv", decimal=",")

# Remove o prefixo "R$" e converte a coluna para numérico
arquivo["Ticket Médio"] = pd.to_numeric(arquivo["Ticket Médio"].str.replace("R\$", "").str.replace(".","").str.replace(",","."))

# Separa o mês de Junho de 2020
df_junho_2020 = arquivo.loc[(arquivo['Mês'] == 'Jun') & (arquivo['Ano'] == 2020), :]

# Calcula a média do Ticket Médio para o mês de Junho de 2020
media_ticket_medio = df_junho_2020["Ticket Médio"].mean()

# Imprime a média do Ticket Médio para o mês de Junho de 2020
print("{:.2f}".format(media_ticket_medio))

"""# Qual foi o mês com o maior número de clientes no ano de 2021?"""

# Remove o prefixo 'R$' e converte a coluna para numérico
arquivo['Ticket Médio'] = pd.to_numeric(arquivo["Ticket Médiio"])